name: mangrove-agb
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyter
  - ipykernel
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - cartopy
  - geopandas
  - gdal
  - rasterio
  - seaborn
  - shap
  - statsmodels
  - openpyxl
  - pip
  - pip:
      - adjustText
      - brokenaxes
